---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    key_groups:
      - age:
          - age1elkkx5sqdyvkd8fev4mq9mgxqswcvn99kjxvy6cwzgv3ay8dfa0s9rpaem
  - path_regex: cluster/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - age1elkkx5sqdyvkd8fev4mq9mgxqswcvn99kjxvy6cwzgv3ay8dfa0s9rpaem
