# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:X1k9AItzPv6n,iv:NmlRl9IkKoqaBfK3S6ejXqRmEJGxn0zrEnxvsxq6kec=,tag:aueB3/aWp7ffpP62jG+BRg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1elkkx5sqdyvkd8fev4mq9mgxqswcvn99kjxvy6cwzgv3ay8dfa0s9rpaem
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5WlV2UUJsOFBMM3QwOFpV
            OGJYVjdTUHp3L0dPcXoreDR3Qlp4WkdPdkRRClBPSHNuWU5ZNUhqUzVxMVdpd21i
            R0dBL0ljamN2aHJEcTVqWTBVNGVkamcKLS0tIGZkVjR2YUhDbmI4SlAyUEdpMytO
            b0ZCaEJ1aklBZit4aVNMMFRwRlhHMmMKot9c1nNpIKG+ZoB0j088bC5GmOs9e29/
            tPxkSbHID2zZjqLWvQNcgduBpdn9V18DDPI14dwRyPWst6euNd6udA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-12T21:39:16Z"
    mac: ENC[AES256_GCM,data:s6Z8Mkrzn168UXB4A5RqsHHssbXdTPToyjxNG1SZ24IevMjxuKg4U2dlmkfBVELkLaYoPUiL8vhDJXJdmfjIbhEek70qNQgs4TLzOD6L6b/g8HXUN+9cb/04lY3xb1hsS49ibH4lD1zVS+Pt/oIek4a5VTmE30fuiIdnAICJcEI=,iv:RPScFFdqeZhg04FNFwidLD/SvzlbMvMvaJsLL9ZNu20=,tag:IImWmympR5RxGF6pXq+2zA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
