---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kyverno-policy-reporter
  namespace: kube-system
spec:
  interval: 15m
  chart:
    spec:
      chart: policy-reporter
      version: 2.13.3
      sourceRef:
        kind: HelmRepository
        name: kyverno-policy-reporter-charts
        namespace: flux-system
      interval: 15m
  values:
    metrics:
      enabled: true
    ui:
      enabled: true
      ingress:
        enabled: true
        ingressClassName: "nginx"
        hosts:
          - host: &host "kv-rp.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix

    global:
      plugins:
        kyverno: true

