---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-release.yaml
  - pdns-webhook.yaml
  - pdns-secret.sops.yaml
  - zerossl-secret.sops.yaml
  - zerossl-prod-pdns.yaml
