apiVersion: v1
kind: Secret
metadata:
    name: pdns-secret
    namespace: cert-manager
type: Opaque
stringData:
    api-key: ENC[AES256_GCM,data:M+bQte6Oeg==,iv:TILSPIjCQozkuwlz8qcRIKjinwUtveC/u7aC7RmShYA=,tag:9nhM6VAtg6AkCq3GFnOw5w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1elkkx5sqdyvkd8fev4mq9mgxqswcvn99kjxvy6cwzgv3ay8dfa0s9rpaem
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGWWpIajdSU3ZmTmx2alJa
            WXVJanltdE8yZ2loL2gxdU5pUWQ5UUVuUXc0CnhITHIyblNjeFVNZVo5WEpqSGd0
            OEM0bkEvci9XYUpYcWdhcXg4YjlQZlEKLS0tIFRoZ3k3YW1ZR3pnWW51ekgvSjlP
            ajgzcHR3eU5wNTNQbGN2ZURqajJtUk0Kvn/Skzd66qLgYCKzdz0iuJ235Vdw3Ph0
            EORVRaL76tnyvHjtfXbk8tp4BpJPtmEAv0p4o8ZCBVC2OvqkdkzPKA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-26T09:42:02Z"
    mac: ENC[AES256_GCM,data:HfuBd95DIbVaXoMfC+mwCxwc43UMT6mc5pXihju2K3OmCneQkG5f1FeDpEw7sRplHvfpTWwojoKQ2yPBRBbaSgnA5dtP1NPPRBKvanUPajoxIscN8k9aloYsLe1UeTg1LgvQWt9WdqZpK/NTyNGPX6Rx7nzcVls+FA5BkdLJf14=,iv:IcrpgaiI3rbtCekhCYaCWs3AqM1kl3XxFvbRZw6qhqI=,tag:HA0+fBIzSxX+eTgFbfoKBg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
