apiVersion: v1
kind: Secret
metadata:
    namespace: cert-manager
    name: zerossl-eabsecret
stringData:
    secret: ENC[AES256_GCM,data:AE7usMwKgDOEFfGYM16FmHYwxNDXcOXqXeB3WRay7CLCCfTPQIUIgwsupwcfASiaEpndKqrZ7nmzydriolNHlFOWLYuS8YVsCcb3Km0dZRLnLb9sL8Q=,iv:TLUkWMl6FlRy545xT+t5GUbwG69WS7NVhR8s8UkooEM=,tag:gxUYyWWbP9k/ZTSwE0vFjA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1elkkx5sqdyvkd8fev4mq9mgxqswcvn99kjxvy6cwzgv3ay8dfa0s9rpaem
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4Um9GYkxzYVZ4NGZTUXZP
            eVkrQVdjUm1waHdoeW5zY3JWUFB4VXJzaXgwCmJYaEYwRnEwclFMRlltcHN5emdm
            eE55MkJycHptd0ZEWDltbFlkMFRYZ0kKLS0tIHlSMUdxZkFJNWQ1UE5NNUc3cysv
            aUpiMmxwT3RVM1doUStwRTFsWDR4NjAKV6W2kDaNyNFoeT2oVr8EAgJkGbcP5J/b
            /4suWPw0qNWe1dc4S0ewiTp4eG7bSd7fAKp4gcKNH5pm6dS2q3CnxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-26T09:42:24Z"
    mac: ENC[AES256_GCM,data:M1E4pNw3/4Cm09X1svRIWVJywM8zSnLa+VslTXaLVwPndlQC3uZuFyW27AVUpINiELuSiLINsFFHg+i19AuF7RiYta8ICO4wo62TbLutfWWbscYht5hJfoXjIxsNB6qoNtbzduNWCveHXEs3dzT56y28K/7x0JsC+MNNwgZa2AI=,iv:cERTZrlHadADX6N4BMfA1u7ryqleQb+84GMVU8+Onjc=,tag:Q5t73BTXo1tRf9mH7sFlyQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
