---
# https://rancher.com/docs/k3s/latest/en/installation/install-options/server-config/
# https://github.com/PyratLabs/ansible-role-k3s

# (bool) Specify if a host (or host group) are part of the control plane
k3s_control_node: true

k3s_disable_kube_proxy: true

# (dict) k3s settings for all control-plane nodes
k3s_server:
  node-ip: "{{ ansible_default_ipv6.address }}"
  #node-ip: "{{ ansible_default_ipv6.address }},{{ ansible_host }}"
  # node-ip: "{{ ansible_host }},{{ ansible_default_ipv6.address }}"
  tls-san:
#     - "{{ k3s_registration_address }}"
    - "{{ ansible_default_ipv6.address }}"
  # Disable Docker - this will use the default containerd CRI
  docker: false
  flannel-backend: "host-gw" # This needs to be in quotes
  disable:
    - traefik
    - servicelb
    - metrics-server
  disable-network-policy: true
  disable-cloud-controller: true
  write-kubeconfig-mode: "644"
  # Network CIDR to use for pod IPs
  # cluster-cidr: "10.45.0.0/16,fd88:3377:4473::/48"
  cluster-cidr: "2001:67c:1104:c000::/56"
  # Network CIDR to use for service IPs
  # service-cidr: "10.46.0.0/16,2001:67c:1104:ad::e:0/112"
  service-cidr: "2001:67c:1104:ad::e:0/112"
  kubelet-arg:
    # Allow k8s services to contain TCP and UDP on the same port
    - "feature-gates=MixedProtocolLBService=true"
  kube-controller-manager-arg:
    # Allow k8s services to contain TCP and UDP on the same port
    - "feature-gates=MixedProtocolLBService=true"
    # Required to monitor kube-controller-manager with kube-prometheus-stack
    - "bind-address=0.0.0.0"
  kube-scheduler-arg:
    # Allow k8s services to contain TCP and UDP on the same port
    - "feature-gates=MixedProtocolLBService=true"
    # Required to monitor kube-scheduler with kube-prometheus-stack
    - "bind-address=0.0.0.0"
  # Required to monitor etcd with kube-prometheus-stack
  etcd-expose-metrics: true
  kube-apiserver-arg:
    # Allow k8s services to contain TCP and UDP on the same port
    - "feature-gates=MixedProtocolLBService=true"
